import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { Button, Card, Screen, State, colors } from '@/components/ui';
import { useAction, useToday } from '@/features/queries';
import type { PlanItem } from '@/lib/types';
const today = () => new Date().toLocaleDateString('en-CA');
export default function TodayScreen() { const date = String(useLocalSearchParams<{ date?: string }>().date ?? today()); const query = useToday(date); const action = useAction(); const complete = async (item: PlanItem) => { if (item.kind === 'personalTask') await action.mutateAsync({ path: `/tasks/${item.entityId}/complete`, body: { completed: true } }); if (item.kind === 'goal') await action.mutateAsync({ path: `/goals/${item.entityId}/complete`, body: { occurrenceKey: item.occurrenceKey ?? date, state: 'completed' } }); }; return <Screen><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</Text><Text style={styles.title}>Your daily flow</Text>{query.data?.sourceStatus.availability === 'unavailable' && <Text style={styles.offline}>Source refresh is unavailable. These are your last saved items.</Text>}<State loading={query.isLoading} error={query.error} empty={query.data && !query.data.items.length ? 'Nothing is planned yet. Add a task or choose a goal.' : undefined}/>{query.data?.items.map(item => <PlanCard key={item.key} item={item} onComplete={() => complete(item)}/>) }{query.data?.campusEvents.length ? <><Text style={styles.section}>Campus today</Text>{query.data.campusEvents.map(event => <Card key={event.id}><Text style={styles.item}>{event.title}</Text><Text style={styles.meta}>{event.timing.kind === 'timed' ? new Date(event.timing.startsAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : event.timing.startDate} · {event.location ?? 'Campus'}</Text></Card>)}</> : null}{query.data?.upcoming.length ? <><Text style={styles.section}>Coming up</Text>{query.data.upcoming.map(item => <Card key={item.key}><Text style={styles.item}>{item.title}</Text><Text style={styles.meta}>{item.state}</Text></Card>)}</> : null}</ScrollView></Screen>; }
function PlanCard({ item, onComplete }: { item: PlanItem; onComplete: () => void }) { const actionable = item.kind === 'personalTask' || item.kind === 'goal'; return <Card><View style={styles.row}><View style={{ flex: 1, gap: 4 }}><Text style={styles.kind}>{item.isMainGoal ? '★ MAIN GOAL' : item.kind === 'academic' ? 'UNIVERSITY' : item.kind.toUpperCase()}</Text><Text style={[styles.item, (item.state === 'completed' || item.state === 'submitted') && styles.done]}>{item.title}</Text><Text style={styles.meta}>{item.state}</Text></View>{actionable && <Button title={item.state === 'completed' ? 'Done' : 'Complete'} tone={item.state === 'completed' ? 'plain' : 'primary'} onPress={onComplete}/>}</View></Card>; }
const styles = StyleSheet.create({ content: { padding: 16, gap: 12 }, kicker: { color: colors.muted, fontWeight: '700' }, title: { fontSize: 29, color: colors.ink, fontWeight: '800', marginBottom: 6 }, section: { fontSize: 18, color: colors.ink, fontWeight: '800', marginTop: 10 }, row: { flexDirection: 'row', gap: 12, alignItems: 'center' }, kind: { color: colors.moss, fontSize: 11, fontWeight: '800', letterSpacing: .6 }, item: { color: colors.ink, fontSize: 17, fontWeight: '700' }, done: { color: colors.muted, textDecorationLine: 'line-through' }, meta: { color: colors.muted }, offline: { backgroundColor: '#FFF3D4', color: '#725700', padding: 12, borderRadius: 12 } });
