import type { PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
export const colors = { ink: '#20302A', muted: '#63746C', canvas: '#F6F8F4', card: '#FFFFFF', moss: '#42745A', sage: '#DDECE2', coral: '#C76750', line: '#DCE4DD' };
export function Screen({ children }: PropsWithChildren) { return <View style={styles.screen}>{children}</View>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Button({ title, onPress, tone = 'primary', disabled }: { title: string; onPress: () => void; tone?: 'primary' | 'plain' | 'danger'; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button, tone === 'plain' && styles.plain, tone === 'danger' && styles.danger, disabled && styles.disabled]}><Text style={[styles.buttonText, tone === 'plain' && styles.plainText]}>{title}</Text></Pressable>; }
export function Field({ label, value, onChangeText, placeholder, multiline = false }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} style={[styles.input, multiline && styles.multiline]} value={value} onChangeText={onChangeText} placeholder={placeholder} multiline={multiline} /></View>; }
export function State({ loading, error, empty }: { loading?: boolean; error?: unknown; empty?: string }) { if (loading) return <View style={styles.state}><ActivityIndicator color={colors.moss}/><Text>Loading your plan…</Text></View>; if (error) return <View style={styles.state}><Text style={styles.error}>Couldn’t refresh. Showing saved information when available.</Text></View>; if (empty) return <View style={styles.state}><Text>{empty}</Text></View>; return null; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas }, card: { backgroundColor: colors.card, borderRadius: 18, padding: 16, gap: 10, borderWidth: 1, borderColor: colors.line }, button: { minHeight: 46, borderRadius: 13, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, backgroundColor: colors.moss }, buttonText: { color: '#fff', fontWeight: '700' }, plain: { backgroundColor: colors.sage }, plainText: { color: colors.ink }, danger: { backgroundColor: colors.coral }, disabled: { opacity: .5 }, field: { gap: 6 }, label: { color: colors.ink, fontWeight: '700' }, input: { minHeight: 46, borderColor: colors.line, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, color: colors.ink, backgroundColor: '#fff' }, multiline: { minHeight: 86, textAlignVertical: 'top', paddingTop: 12 }, state: { alignItems: 'center', gap: 10, padding: 24 }, error: { color: colors.coral, textAlign: 'center' } });
