import { Body, Controller, Delete, Get, Injectable, NotFoundException, Param, Patch, Post, Put, Query, UseGuards } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { academicItemSchema, completeGoalSchema, completePersonalTaskSchema, courseSchema, createGoalSchema, createPersonalTaskSchema, createWellnessEntrySchema, eventSchema, goalCompletionSchema, goalSchema, notificationPreferencesSchema, personalTaskSchema, reminderSchema, saveEventSchema, savedEventSchema, setMainGoalSchema, snoozeGoalSchema, snoozePersonalTaskSchema, updateGoalSchema, updateNotificationPreferencesSchema, updatePersonalTaskSchema, updateSavedEventSchema, wellnessEntrySchema } from '@campusflow/contracts';
import { AuthGuard, CurrentUser, RequestUser, ZodPipe, parseUuid, toIso } from './common';
import { PrismaService } from './prisma.service';

const asJson = (value: unknown): Prisma.InputJsonValue => value as Prisma.InputJsonValue;
const taskDto = (r:{id:string;title:string;description:string|null;priority:string;category:string;due:Prisma.JsonValue|null;scheduled:Prisma.JsonValue|null;recurrence:Prisma.JsonValue|null;reminder:Prisma.JsonValue|null;estimatedMinutes:number|null;completedAt:Date|null;snoozedUntil:Date|null;mainGoalDate:string|null;createdAt:Date;updatedAt:Date}) => personalTaskSchema.parse({...r,completedAt:r.completedAt?.toISOString()??null,snoozedUntil:r.snoozedUntil?.toISOString()??null,createdAt:toIso(r.createdAt),updatedAt:toIso(r.updatedAt)});
const goalDto = (r:{id:string;title:string;category:string;schedule:Prisma.JsonValue;timeZone:string;reminder:Prisma.JsonValue|null;pausedAt:Date|null;snoozedUntil:Date|null;createdAt:Date;updatedAt:Date}) => goalSchema.parse({...r,pausedAt:r.pausedAt?.toISOString()??null,snoozedUntil:r.snoozedUntil?.toISOString()??null,createdAt:toIso(r.createdAt),updatedAt:toIso(r.updatedAt)});
const eventDto = (r:{id:string;title:string;description:string|null;category:string|null;source:string;externalId:string;timing:Prisma.JsonValue;location:string|null;url:string|null}) => eventSchema.parse(r);

@Injectable() export class ReminderService {
  constructor(private readonly prisma:PrismaService) {}
  async replace(userId:string,targetKind:string,targetId:string,reminder:unknown):Promise<void> {
    await this.prisma.reminder.deleteMany({where:{userId,targetKind,targetId}});
    if (reminder && typeof reminder==='object' && 'kind' in reminder && reminder.kind==='instant' && 'at' in reminder && typeof reminder.at==='string') await this.prisma.reminder.create({data:{userId,targetKind,targetId,fireAt:new Date(reminder.at),...(targetKind==='personalTask'?{personalTaskId:targetId}:targetKind==='goal'?{goalId:targetId}:{})}});
  }
}

@Controller('tasks') @UseGuards(AuthGuard) export class TasksController {
  constructor(private readonly prisma:PrismaService,private readonly reminders:ReminderService) {}
  @Get() async list(@CurrentUser() u:RequestUser,@Query('search') search?:string,@Query('category') category?:string,@Query('completed') completed?:string){const where:Prisma.PersonalTaskWhereInput={userId:u.id,...(search?{OR:[{title:{contains:search,mode:'insensitive'}},{description:{contains:search,mode:'insensitive'}}]}:{}),...(category?{category}:{}),...(completed==='true'?{completedAt:{not:null}}:completed==='false'?{completedAt:null}:{})}; return (await this.prisma.personalTask.findMany({where,orderBy:{updatedAt:'desc'}})).map(taskDto);}
  @Post() async create(@CurrentUser() u:RequestUser,@Body(new ZodPipe(createPersonalTaskSchema)) b:z.infer<typeof createPersonalTaskSchema>){const r=await this.prisma.personalTask.create({data:{userId:u.id,title:b.title,description:b.description??null,priority:b.priority??'medium',category:b.category??'personal',due:b.due?asJson(b.due):Prisma.JsonNull,scheduled:b.scheduled?asJson(b.scheduled):Prisma.JsonNull,recurrence:b.recurrence?asJson(b.recurrence):Prisma.JsonNull,reminder:b.reminder?asJson(b.reminder):Prisma.JsonNull,estimatedMinutes:b.estimatedMinutes??null}}); await this.reminders.replace(u.id,'personalTask',r.id,b.reminder); return taskDto(r);}
  @Get(':id') async get(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string){return taskDto(await this.owned(u.id,id));}
  @Patch(':id') async update(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(updatePersonalTaskSchema)) b:z.infer<typeof updatePersonalTaskSchema>){await this.owned(u.id,id);const data:Prisma.PersonalTaskUpdateInput={...b,due:b.due===undefined?undefined:b.due===null?Prisma.JsonNull:asJson(b.due),scheduled:b.scheduled===undefined?undefined:b.scheduled===null?Prisma.JsonNull:asJson(b.scheduled),recurrence:b.recurrence===undefined?undefined:b.recurrence===null?Prisma.JsonNull:asJson(b.recurrence),reminder:b.reminder===undefined?undefined:b.reminder===null?Prisma.JsonNull:asJson(b.reminder)};const task=await this.prisma.personalTask.update({where:{id},data});if(b.reminder!==undefined)await this.reminders.replace(u.id,'personalTask',id,b.reminder);return taskDto(task);}
  @Delete(':id') async remove(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string){await this.owned(u.id,id);await this.prisma.personalTask.delete({where:{id}});return {deleted:true};}
  @Post(':id/complete') async complete(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(completePersonalTaskSchema)) b:z.infer<typeof completePersonalTaskSchema>){const task=await this.owned(u.id,id);if(task.recurrence){if(!b.occurrenceKey)throw new NotFoundException('A recurring task completion requires an occurrence date');if(b.completed)await this.prisma.taskCompletion.upsert({where:{userId_taskId_occurrenceKey:{userId:u.id,taskId:id,occurrenceKey:b.occurrenceKey}},create:{userId:u.id,taskId:id,occurrenceKey:b.occurrenceKey},update:{}});else await this.prisma.taskCompletion.deleteMany({where:{userId:u.id,taskId:id,occurrenceKey:b.occurrenceKey}});return taskDto(task);}return taskDto(await this.prisma.personalTask.update({where:{id},data:{completedAt:b.completed?new Date():null}}));}
  @Post(':id/snooze') async snooze(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(snoozePersonalTaskSchema)) b:z.infer<typeof snoozePersonalTaskSchema>){await this.owned(u.id,id);return taskDto(await this.prisma.personalTask.update({where:{id},data:{snoozedUntil:new Date(b.until)}}));}
  @Post(':id/main-goal') async main(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(setMainGoalSchema)) b:z.infer<typeof setMainGoalSchema>){await this.owned(u.id,id);return this.prisma.$transaction(async tx=>{if(b.date)await tx.personalTask.updateMany({where:{userId:u.id,mainGoalDate:b.date,id:{not:id}},data:{mainGoalDate:null}});return taskDto(await tx.personalTask.update({where:{id},data:{mainGoalDate:b.date}}));});}
  private async owned(userId:string,id:string){const r=await this.prisma.personalTask.findFirst({where:{id,userId}});if(!r)throw new NotFoundException('Task not found');return r;}
}

@Controller() @UseGuards(AuthGuard) export class AcademicController {
 constructor(private readonly prisma:PrismaService){}
 @Get('courses') async courses(@CurrentUser() u:RequestUser){return (await this.prisma.course.findMany({where:{userId:u.id},orderBy:{name:'asc'}})).map(r=>courseSchema.parse(r));}
 @Get('academic-items') async items(@CurrentUser() u:RequestUser){return (await this.prisma.academicItem.findMany({where:{userId:u.id},orderBy:{updatedAt:'desc'}})).map(r=>academicItemSchema.parse({...r,updatedAt:toIso(r.updatedAt)}));}
 @Patch('academic-items/:id/main-goal') async main(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(setMainGoalSchema)) b:z.infer<typeof setMainGoalSchema>){const owned=await this.prisma.academicItem.findFirst({where:{id,userId:u.id}});if(!owned)throw new NotFoundException();return this.prisma.$transaction(async tx=>{if(b.date)await tx.academicItem.updateMany({where:{userId:u.id,mainGoalDate:b.date,id:{not:id}},data:{mainGoalDate:null}});const r=await tx.academicItem.update({where:{id},data:{mainGoalDate:b.date}});return academicItemSchema.parse({...r,updatedAt:toIso(r.updatedAt)});});}
}

@Controller('goals') @UseGuards(AuthGuard) export class GoalsController {
 constructor(private readonly prisma:PrismaService){}
 @Get() async list(@CurrentUser() u:RequestUser){return (await this.prisma.goal.findMany({where:{userId:u.id},orderBy:{updatedAt:'desc'}})).map(goalDto);}
 @Post() async create(@CurrentUser() u:RequestUser,@Body(new ZodPipe(createGoalSchema)) b:z.infer<typeof createGoalSchema>){return goalDto(await this.prisma.goal.create({data:{userId:u.id,title:b.title,category:b.category??'health',schedule:asJson(b.schedule),timeZone:b.timeZone,reminder:b.reminder?asJson(b.reminder):Prisma.JsonNull}}));}
 @Patch(':id') async update(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(updateGoalSchema)) b:z.infer<typeof updateGoalSchema>){await this.owned(u.id,id);const data:Prisma.GoalUpdateInput={...b,schedule:b.schedule?asJson(b.schedule):undefined,reminder:b.reminder===undefined?undefined:b.reminder===null?Prisma.JsonNull:asJson(b.reminder)};return goalDto(await this.prisma.goal.update({where:{id},data}));}
 @Delete(':id') async remove(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string){await this.owned(u.id,id);await this.prisma.goal.delete({where:{id}});return {deleted:true};}
 @Post(':id/complete') async complete(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(completeGoalSchema)) b:z.infer<typeof completeGoalSchema>){await this.owned(u.id,id);const r=await this.prisma.goalCompletion.upsert({where:{userId_goalId_occurrenceKey:{userId:u.id,goalId:id,occurrenceKey:b.occurrenceKey}},create:{userId:u.id,goalId:id,occurrenceKey:b.occurrenceKey,state:b.state,completedAt:b.state==='completed'?new Date():null},update:{state:b.state,completedAt:b.state==='completed'?new Date():null}});return goalCompletionSchema.parse({...r,completedAt:r.completedAt?.toISOString()??null,createdAt:toIso(r.createdAt)});}
 @Post(':id/snooze') async snooze(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body(new ZodPipe(snoozeGoalSchema)) b:z.infer<typeof snoozeGoalSchema>){await this.owned(u.id,id);return goalDto(await this.prisma.goal.update({where:{id},data:{snoozedUntil:new Date(b.until)}}));}
 @Post(':id/pause') async pause(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string,@Body() b:{paused?:boolean}){await this.owned(u.id,id);return goalDto(await this.prisma.goal.update({where:{id},data:{pausedAt:b.paused===false?null:new Date()}}));}
 @Get(':id/history') async history(@CurrentUser() u:RequestUser,@Param('id',new ZodPipe(parseUuid)) id:string){await this.owned(u.id,id);return (await this.prisma.goalCompletion.findMany({where:{userId:u.id,goalId:id},orderBy:{occurrenceKey:'desc'}})).map(r=>goalCompletionSchema.parse({...r,completedAt:r.completedAt?.toISOString()??null,createdAt:toIso(r.createdAt)}));}
 private async owned(userId:string,id:string){const r=await this.prisma.goal.findFirst({where:{id,userId}});if(!r)throw new NotFoundException('Goal not found');return r;}
}

@Controller('wellness') @UseGuards(AuthGuard) export class WellnessController {constructor(private readonly prisma:PrismaService){} @Get() async list(@CurrentUser()u:RequestUser){return(await this.prisma.wellnessEntry.findMany({where:{userId:u.id},orderBy:{date:'desc'}})).map(r=>wellnessEntrySchema.parse({...r,createdAt:toIso(r.createdAt)}));} @Post() async save(@CurrentUser()u:RequestUser,@Body(new ZodPipe(createWellnessEntrySchema))b:z.infer<typeof createWellnessEntrySchema>){const r=await this.prisma.wellnessEntry.upsert({where:{userId_date:{userId:u.id,date:b.date}},create:{userId:u.id,...b},update:b});return wellnessEntrySchema.parse({...r,createdAt:toIso(r.createdAt)});}}

@Controller('events') @UseGuards(AuthGuard) export class EventsController {
 constructor(private readonly prisma:PrismaService){}
 @Get() async list(@CurrentUser()u:RequestUser,@Query('category')category?:string,@Query('from')from?:string,@Query('through')through?:string){const rows=await this.prisma.event.findMany({where:{OR:[{sourceScope:'public'},{sourceScope:`user:${u.id}`}],...(category?{category}:{}),...(from||through?{sortAt:{...(from?{gte:new Date(from)}:{}),...(through?{lt:new Date(through)}:{})}}:{})},orderBy:{sortAt:'asc'},include:{savedBy:{where:{userId:u.id}}}});return rows.map(r=>({...eventDto(r),saved:r.savedBy.length>0,includedInPlan:r.savedBy[0]?.includedInPlan??false}));}
 @Put(':id/saved') async save(@CurrentUser()u:RequestUser,@Param('id',new ZodPipe(parseUuid))id:string,@Body(new ZodPipe(saveEventSchema))b:z.infer<typeof saveEventSchema>){await this.event(id,u.id);const r=await this.prisma.savedEvent.upsert({where:{userId_eventId:{userId:u.id,eventId:id}},create:{userId:u.id,eventId:id,includedInPlan:b.includedInPlan,reminder:b.reminder?asJson(b.reminder):Prisma.JsonNull},update:{includedInPlan:b.includedInPlan,reminder:b.reminder===undefined?undefined:b.reminder===null?Prisma.JsonNull:asJson(b.reminder)}});return savedEventSchema.parse({...r,savedAt:toIso(r.savedAt)});}
 @Patch(':id/saved') async patch(@CurrentUser()u:RequestUser,@Param('id',new ZodPipe(parseUuid))id:string,@Body(new ZodPipe(updateSavedEventSchema))b:z.infer<typeof updateSavedEventSchema>){const existing=await this.prisma.savedEvent.findUnique({where:{userId_eventId:{userId:u.id,eventId:id}}});if(!existing)throw new NotFoundException('Saved event not found');const r=await this.prisma.savedEvent.update({where:{userId_eventId:{userId:u.id,eventId:id}},data:{includedInPlan:b.includedInPlan,reminder:b.reminder===undefined?undefined:b.reminder===null?Prisma.JsonNull:asJson(b.reminder)}});return savedEventSchema.parse({...r,savedAt:toIso(r.savedAt)});}
 @Delete(':id/saved') async unsave(@CurrentUser()u:RequestUser,@Param('id',new ZodPipe(parseUuid))id:string){await this.prisma.savedEvent.deleteMany({where:{userId:u.id,eventId:id}});return {deleted:true};}
 private async event(id:string,userId:string){const r=await this.prisma.event.findFirst({where:{id,OR:[{sourceScope:'public'},{sourceScope:`user:${userId}`}]}});if(!r)throw new NotFoundException('Event not found');return r;}
}

@Controller() @UseGuards(AuthGuard) export class PreferencesController {
 constructor(private readonly prisma:PrismaService){}
 @Get('notification-preferences') async get(@CurrentUser()u:RequestUser){const r=await this.prisma.notificationPreference.upsert({where:{userId:u.id},create:{userId:u.id},update:{}});return notificationPreferencesSchema.parse(r);}
 @Patch('notification-preferences') async patch(@CurrentUser()u:RequestUser,@Body(new ZodPipe(updateNotificationPreferencesSchema))b:z.infer<typeof updateNotificationPreferencesSchema>){return notificationPreferencesSchema.parse(await this.prisma.notificationPreference.upsert({where:{userId:u.id},create:{userId:u.id,...b},update:b}));}
 @Get('reminders') async reminders(@CurrentUser()u:RequestUser){return(await this.prisma.reminder.findMany({where:{userId:u.id,enabled:true},orderBy:{fireAt:'asc'}})).map(r=>reminderSchema.parse({...r,fireAt:toIso(r.fireAt)}));}
}
